@extends('layouts.header_admin')
@section('css')
<link href="{{ asset('admin/css/plugins/chosen/bootstrap-chosen.css')}}" rel="stylesheet" defer>
<link href="{{ asset('admin/css/plugins/sweetalert/sweetalert.css')}}" rel="stylesheet" defer>
@endsection
@section('content')
<div class="row">
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-success pull-right">as of Today</span>
                <h5>Total Generated Payroll</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">{{$payrolls->count()}}</h1>
                {{-- <div class="stat-percent font-bold text-success">98% <i class="fa fa-bolt"></i></div> --}}
                <small>&nbsp;</small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-warning pull-right">@if($payrolls->first() != null)<small>{{date('M. d, Y',strtotime(($payrolls->first())->payroll_from))}} - {{date('M. d, Y',strtotime(($payrolls->first())->payroll_to))}}</small>@endif</span>
                <h5>Generated this cutoff  </h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">@if($payrolls->first() != null){{count($payrolls->where('payroll_to',($payrolls->first())->payroll_to)->where('status',""))}}@endif</h1>
                {{-- <div class="stat-percent font-bold text-navy">44% <i class="fa fa-level-up"></i></div> --}}
                <small>&nbsp;</small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-primary pull-right">@if($payrolls->first() != null)<small>{{date('M. d, Y',strtotime(($payrolls->first())->payroll_from))}} - {{date('M. d, Y',strtotime(($payrolls->first())->payroll_to))}}</small>@endif</span>
                <h5>Active Stores</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">{{count($stores)}}</h1>
                {{-- <div class="stat-percent font-bold text-navy">44% <i class="fa fa-level-up"></i></div> --}}
                <small>&nbsp;</small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox float-e-margins">
            <div class="ibox-title">
                <span class="label label-danger pull-right">@if($payrolls->first() != null)<small>{{date('M. d, Y',strtotime(($payrolls->first())->payroll_from))}} - {{date('M. d, Y',strtotime(($payrolls->first())->payroll_to))}}</small>@endif</span>
                <h5>Posted</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">@if($payrolls->first() != null){{count($payrolls->where('payroll_to',($payrolls->first())->payroll_to)->where('status','!=',''))}}@endif</h1>
                {{-- <div class="stat-percent font-bold text-navy">44% <i class="fa fa-level-up"></i></div> --}}
                <small>&nbsp;</small>
            </div>
        </div>
    </div>
</div>
<div class='row'>
    <div class="col-lg-12 grid-margin stretch-card">
        <div class="ibox float-e-margins">
            <div class="ibox-content">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered table-hover home-payroll">
                        <thead>
                            <tr>
                                <th>Action</th>
                                <th>Company</th>
                                <th>Store</th>
                                <th>Generated By</th>
                                <th>Cut Off</th>
                                <th>Employee Count</th>
                                <th>Total Basic Pay</th>
                                <th>Contributions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach($payrolls as $payroll)
                        
                                <tr>
                                    <td > 
                                        @if($payroll->status == "")
                                        <a title='Edit Payroll' href='{{url("edit-payroll/".$payroll->id)}}' ><button type="button"  class="btn btn-success btn-icon btn-sm">
                                            <i class="fa fa-edit"></i>
                                            </button>
                                        </a>
                                        <a title='Delete Payroll' class='delete-payroll' id='{{$payroll->id}}' ><button type="button"  class="btn btn-danger btn-icon btn-sm">
                                            <i class="fa fa-trash"></i>
                                            </button>
                                        </a>
                                        <a title='Save Payroll' class='save-payroll' id='{{$payroll->id}}' ><button type="button"  class="btn btn-warning btn-icon btn-sm">
                                            <i class="fa fa-save"></i>
                                            </button>
                                        </a>
                                        @else
                                        @if($payroll->display == 0)
                                        <a title='Display Payslip' href='{{url("display/".$payroll->id)}}' ><button type="button"  class="btn btn-success btn-icon btn-sm">
                                            <i class="fa fa-exchange"></i>
                                            </button>
                                        </a>
                                        @else
                                        <a title='Remove Payslip' href='{{url("display/".$payroll->id)}}' ><button type="button"  class="btn btn-success btn-icon btn-sm">
                                            <i class="fa fa-minus-square"></i>
                                            </button>
                                        </a>
                                        @endif
                                        <a title='Print Payroll' href='{{url("payroll/".$payroll->id)}}' target="_blank"><button type="button"  class="btn btn-danger btn-icon btn-sm">
                                        <i class="fa fa-file-pdf-o"></i>
                                        </button></a>
                                        <a title='Print Billing' href='{{url("billing/".$payroll->id)}}' target="_blank"><button type="button"  class="btn btn-info btn-icon btn-sm">
                                        <i class="fa fa-file-pdf-o"></i>
                                        </button></a>
                                        @endif
                                    </td>
                                    <td>{{$payroll->company}}</td>
                                    <td>{{$payroll->store}}</td>
                                    <td>{{$payroll->user->name}}</td>
                                    <td>{{date('M d, Y',strtotime($payroll->payroll_from))}} - {{date('M d, Y',strtotime($payroll->payroll_to))}}</td>
                                    <td>{{count($payroll->informations)}}</td>
                                    <td>{{number_format((($payroll->informations)->sum('basic_pay')),2)}} </td>
                                    <td><small>
                                        SSS : {{number_format((($payroll->informations)->sum('sss_contribution')),2)}} <br>
                                        HDMF : {{number_format((($payroll->informations)->sum('hdmf_contribution')),2)}} <br>
                                        NHIP : {{number_format((($payroll->informations)->sum('nhip_contribution')),2)}}
                                        </small>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('js')
<script src="{{ asset('admin/js/plugins/chosen/chosen.jquery.js')}}"></script>
<script src="{{ asset('admin/js/inspinia.js')}}"></script>
<script src="{{ asset('admin/js/plugins/pace/pace.min.js')}}"></script>
<script src="{{ asset('admin/js/plugins/sweetalert/sweetalert.min.js')}}"></script>
<script>
    $('.delete-payroll').click(function () {
        
        var id = this.id;
            swal({
                title: "Are you sure?",
                text: "You will not be able to recover this payroll",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, delete it!",
                closeOnConfirm: false
            }, function (){
                $.ajax({
                    dataType: 'json',
                    type:'POST',
                    url:  '{{url("delete-payroll")}}',
                    data:{id:id},
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                }).done(function(data){
                    console.log(data);
                    swal("Deleted!", "Your record been deleted.", "success");
                    location.reload();
                }).fail(function(data)
                {
                    
                swal("Deleted!", "Your record been deleted.", "success");
                location.reload();
                });
            });
        });
    $('.save-payroll').click(function () {
        
        var id = this.id;
            swal({
                title: "Are you sure to save this payroll?",
                text: "After saving, you cannot edit this payroll anymore",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Yes, save it!",
                closeOnConfirm: false
            }, function (){
                $.ajax({
                    dataType: 'json',
                    type:'POST',
                    url:  '{{url("save-payroll")}}',
                    data:{id:id},
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                }).done(function(data){
                    console.log(data);
                    swal("Saved!", "Successfully Saved.", "success");
                    location.reload();
                }).fail(function(data)
                {
                    
                swal("Saved!", "Successfully Saved.", "success");
                location.reload();
                });
            });
        });
</script>
@endsection

